src/GestionAchats/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home, name='home'),
    path('add/category', add_category, name='add_category'),
    path('delete/category/<int:pk>/', delete_category, name='delete_category'),
    path('categories', category_list, name='category_list'),
    path('add/product', add_product, name='add_product'),
    path('delete/product/<int:pk>/', delete_product, name='delete_product'),
    path('products', product_list, name='product_list'),
    path('add/client', add_client, name='add_client'),
    path('delete/client/<int:pk>/', delete_client, name='delete_client'),
    path('clients', client_list, name='client_list'),
    path('add/order', add_order, name='add_order'),
    path('delete/order/<int:pk>/', delete_order, name='delete_order'),
    path('orders/<int:pk>/', order_detail, name='order_detail'),
    path('orders', list_order, name='list_order'),
    path('add/product/order/<int:pk>/', add_products_order, name='add_product_order'),
    path('orders/<str:name>/', orders_by_customer, name='orders_by_customer'),
    path('register', create_user, name='create_user'),
    path('login', user_login, name='user_login'),
    path('logout', user_logout, name='user_logout'),
    path('users', user_list, name='user_list'),
    path('delete/user/<int:pk>/', delete_user, name='delete_user'),
    path('search', search_orders, name='search_orders'),
    path('login/', LoginPageView.as_view(), name='login'),

    

]

src/projetWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("GestionAchats.urls")),
]

src/GestionAchats/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    def __str__(self):
        return self.name

class Client(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    address = models.TextField()
    def __str__(self):
        return self.name
    
class Order(models.Model):
    customer = models.ForeignKey(Client, on_delete=models.CASCADE)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    date_created = models.DateTimeField(auto_now_add=True)
    products = models.ManyToManyField(Product, through='OrderProduct')
    
    def __str__(self):
        return f"Commande #{self.pk} - {self.customer.name}"

    def get_total_price(self):
        order_products = OrderProduct.objects.filter(order=self)
        return sum([op.product.price * op.quantity for op in order_products])
    
    def get_orders_by_customer_name(name):
        return Order.objects.filter(customer__name__icontains=name)

class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)

    def __str__(self):
        return self.order

 

src/GestionAchats/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'description']

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'category']
    
class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['name', 'email', 'phone', 'address']

class OrderForm(forms.ModelForm):
    customer = forms.ModelChoiceField(queryset=Client.objects.all())
    product = forms.ModelChoiceField(queryset=Product.objects.all())
    quantity = models.IntegerField()

    class Meta:
        model = Order
        fields = ['customer','product']
        widget=forms.Select(attrs={'class': 'form-control'})

class OrderProductForm(forms.ModelForm):
    class Meta:
        model = OrderProduct
        fields = [ 'product', 'quantity']

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = UserCreationForm.Meta.fields + ('email',)

src/GestionAchats/views.py
from django.shortcuts import *
from .models import *
from .forms import *
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.contrib.auth import logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView


@login_required
def home(request):
    return render(request, 'achats/home.html')

@login_required
def category_list(request):
    categories = Category.objects.all()
    return render(request, 'achats/category_list.html', {'categories': categories})

@login_required
def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('category_list')
    else:
        form = CategoryForm()
    return render(request, 'achats/add_category.html', {'form': form})

@login_required
def delete_category(request, pk):
    category = Category.objects.get(pk=pk)
    category.delete()
    return redirect('category_list')

@login_required
def product_list(request):
    products = Product.objects.all()
    return render(request, 'achats/product_list.html', {'products': products})

@login_required
def add_product(request):
    categories = Category.objects.all()
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('product_list')
    else:
        form = ProductForm()
    return render(request, 'achats/add_product.html', {'form': form, 'categories' : categories})

@login_required
def delete_product(request, pk):
    product = Product.objects.get(pk=pk)
    product.delete()
    return redirect('product_list')

@login_required
def client_list(request):
    clients = Client.objects.all()
    return render(request, 'achats/client_list.html', {'clients': clients})

@login_required
def add_client(request):
    if request.method == 'POST':
        form = ClientForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('client_list')
    else:
        form = ClientForm()
    return render(request, 'achats/add_client.html', {'form': form})

@login_required
def delete_client(request, pk):
    client = Client.objects.get(pk=pk)
    client.delete()
    return redirect('client_list')

@login_required
def add_order(request):
    clients = Client.objects.all()
    products = Product.objects.all()
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save()
            productId = request.POST['product']
            product = Product.objects.get(id=productId)
            quantity = request.POST['quantity']
            orderProduct = OrderProduct.objects.create(order=order, product=product, quantity=quantity)
            orderProduct.save()
            order.total_price = order.get_total_price()
            order.save()
            return redirect('list_order')
        else:
            print("Form not valid")
            print(form.errors)
    else:
        form = OrderForm()
    return render(request, 'achats/add_order.html', {'form': form, 'clients' : clients, 'products' : products})

@login_required
def delete_order(request, pk):
    order = Order.objects.get(pk=pk)
    order.delete()
    return redirect('list_order')

@login_required
def add_products_order(request, pk):
    products = Product.objects.all()
    order = Order.objects.get(pk=pk)
    if request.method == 'POST':
        form = OrderProductForm(request.POST)
        if form.is_valid():
            productId = request.POST['product']
            product = Product.objects.get(id=productId)
            quantity = request.POST['quantity']
            orderProduct = OrderProduct.objects.create(order=order, product=product, quantity=quantity)
            orderProduct.save()
            order.total_price = order.get_total_price()
            order.save()
            return redirect('order_detail', pk)
        else:
            print("Form not valid")
            print(form.errors)
    else:
        form = OrderProductForm()
    return render(request, 'achats/add_product_order.html', {'form': form, 'order': order, 'products' : products})

@login_required
def order_detail(request, pk):
    order = Order.objects.get(pk=pk)
    return render(request, 'achats/order_detail.html', {'order': order})

@login_required
def list_order(request):
    orders = Order.objects.all()
    return render(request, 'achats/list_order.html', {'orders': orders})

@login_required
def orders_by_customer(request, name):
    orders = Order.get_orders_by_customer_name(name)
    return render(request, 'achats/orders.html', {'orders': orders, 'name' : name})

@login_required
def search_orders(request):
    if request.method == 'POST':
        customer_name = request.POST['customer_name']
        return orders_by_customer(request, customer_name)
    else:
        return render(request, 'achats/home.html')

@login_required
def create_user(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = CustomUserCreationForm()
    return render(request, 'achats/create_user.html', {'form': form})

@login_required
def user_list(request):
    users = User.objects.all()
    return render(request, 'achats/user_list.html', {'users': users})

@login_required
def delete_user(request, pk):
    user = User.objects.get(pk=pk)
    user.delete()
    return redirect('user_list')

def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home')
            else:
                messages.error(request,'username or password not correct')
                return redirect('user_login')
    else:
        form = AuthenticationForm()
    return render(request, 'achats/login.html', {'form': form})

@login_required
def user_logout(request):
    logout(request)
    return redirect('user_login')

class LoginPageView(LoginView):
    template_name = 'achats/login.html'

src/GestionAchats/templates/Achats/add_category.html
{% extends "Achats/base.html" %}
{% load static %}
{% block content %}
          <!-- Content wrapper -->
          <div class="content-wrapper">
            <!-- Content -->

            <div class="container-xxl flex-grow-1 container-p-y">
              <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Categories/</span> Ajouter</h4>

              <!-- Basic Layout & Basic with Icons -->
              <div class="row">
                <!-- Basic Layout -->
                <div class="col-xxl">
                  <div class="card mb-4">
                    <div class="card-body">
                      <form method="post" >
                        {% csrf_token %}
                        <div class="row mb-3">
                          <label class="col-sm-2 col-form-label" for="name">Nom</label>
                          <div class="col-sm-10">
                            <input type="text" class="form-control" name="name" id="name"/>
                          </div>
                        </div>
                        <div class="row mb-3">
                          <label class="col-sm-2 col-form-label" for="description">Description</label>
                          <div class="col-sm-10">
                            <textarea
                            id="description"
                              name="description"
                            class="form-control"
                            aria-describedby="basic-icon-default-message2"
                          ></textarea>
                          </div>
                        </div>
                        <div class="row justify-content-end">
                          <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary">Ajouter</button>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- / Content -->
{% endblock %}

src/GestionAchats/templates/Achats/add_client.html
{% extends "Achats/base.html" %}
{% load static %}
{% block content %}
          <!-- Content wrapper -->
          <div class="content-wrapper">
            <!-- Content -->

            <div class="container-xxl flex-grow-1 container-p-y">
              <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Clients/</span> Ajouter</h4>

              <!-- Basic Layout & Basic with Icons -->
              <div class="row">
                <!-- Basic Layout -->
                <div class="col-xxl">
                  <div class="card mb-4">
                    <div class="card-body">
                      <form method="post" >
                        {% csrf_token %}
                        <div class="row mb-3">
                          <label class="col-sm-2 col-form-label" for="name">Nom</label>
                          <div class="col-sm-10">
                            <input type="text" class="form-control" name="name" id="name"/>
                          </div>
                        </div>
                        <div class="row mb-3">
                          <label class="col-sm-2 col-form-label" for="email">Email</label>
                          <div class="col-sm-10">
                            <input type="text" class="form-control" name="email" id="email"/>
                          </div>
                        </div>
                        <div class="row mb-3">
                          <label class="col-sm-2 col-form-label" for="phone">Telephone</label>
                          <div class="col-sm-10">
                            <div class="input-group input-group-merge">
                              <input
                                type="text"
                                id="phone"
                                class="form-control"
                                name="phone"
                              />
                            </div>
                          </div>
                        </div>
                        <div class="row mb-3">
                            <label for="address" class="col-sm-2 col-form-label">Adresse</label>
                            <div class="col-sm-10">
                                <textarea
                                id="address"
                                  name="address"
                                class="form-control"
                                aria-describedby="basic-icon-default-message2"
                              ></textarea>
                              </div>
                          </div>
                        <div class="row justify-content-end">
                          <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary">Ajouter</button>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- / Content -->
{% endblock %}

src/GestionAchats/templates/Achats/add_order.html
{% extends "Achats/base.html" %}
{% load static %}
{% block content %}
          <!-- Content wrapper -->
          <div class="content-wrapper">
            <!-- Content -->

            <div class="container-xxl flex-grow-1 container-p-y">
              <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Commandes/</span> Ajouter</h4>

              <!-- Basic Layout & Basic with Icons -->
              <div class="row">
                <!-- Basic Layout -->
                <div class="col-xxl">
                  <div class="card mb-4">
                    <div class="card-body">
                      <form method="post" >
                        {% csrf_token %}
                        <div class="row mb-3">
                          <label for="customer" class="col-sm-2 col-form-label">Client</label>
                          <div class="col-sm-10">
                              <select id="customer" name="customer" class="form-select">
                                <option value="">Choisissez un Client</option>
                                  {% for client in clients %}
                                      <option value="{{ client.pk }}">{{ client.name }}</option>
                                  {% endfor %}
                              </select>

                          </div>
                        </div>
                      <div class="row mb-3">
                          <label for="product" class="col-sm-2 col-form-label">Produit</label>
                          <div class="col-sm-10">
                              <select id="product" name="product" class="form-select">
                                <option value="">Choisissez un Produit</option>
                                  {% for product in products %}
                                      <option value="{{ product.pk }}">{{ product.name }}</option>
                                  {% endfor %}
                              </select>

                          </div>
                        </div>
                        <div class="row mb-3">
                          <label class="col-sm-2 col-form-label" for="quantity">Quantité</label>
                          <div class="col-sm-10">
                            <div class="input-group input-group-merge">
                              <input
                                type="number"
                                id="quantity"
                                class="form-control"
                                name="quantity"
                                value="{{ form.quantity }}"
                              />
                            </div>
                          </div>
                        </div>

                        <div class="row justify-content-end">
                          <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary">Ajouter</button>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- / Content -->
{% endblock %}

src/GestionAchats/templates/Achats/add_product.html
{% extends "Achats/base.html" %}
{% load static %}
{% block content %}
          <!-- Content wrapper -->
          <div class="content-wrapper">
            <!-- Content -->

            <div class="container-xxl flex-grow-1 container-p-y">
              <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Produits/</span> Ajouter</h4>

              <!-- Basic Layout & Basic with Icons -->
              <div class="row">
                <!-- Basic Layout -->
                <div class="col-xxl">
                  <div class="card mb-4">
                    <div class="card-body">
                      <form method="post" >
                        {% csrf_token %}
                        <div class="row mb-3">
                          <label class="col-sm-2 col-form-label" for="name">Nom</label>
                          <div class="col-sm-10">
                            <input type="text" class="form-control" name="name" id="name"/>
                          </div>
                        </div>
                        <div class="row mb-3">
                          <label class="col-sm-2 col-form-label" for="description">Description</label>
                          <div class="col-sm-10">
                            <textarea
                            id="description"
                              name="description"
                            class="form-control"
                            aria-describedby="basic-icon-default-message2"
                          ></textarea>
                          </div>
                        </div>
                        <div class="row mb-3">
                          <label class="col-sm-2 col-form-label" for="price">Prix</label>
                          <div class="col-sm-10">
                            <div class="input-group input-group-merge">
                              <input
                                type="number"
                                id="price"
                                class="form-control"
                                name="price"
                              />
                            </div>
                          </div>
                        </div>
                        <div class="row mb-3">
                            <label for="category" class="col-sm-2 col-form-label">Categorie</label>
                            <div class="col-sm-10">
                                <select id="category" name="category" class="form-select">
                                    <option>Categories</option>
                                    {% for category in categories %}
                                        <option value="{{ category.id }}">{{ category.name }}</option>
                                    {% endfor %}
                                </select>

                            </div>
                          </div>
                        <div class="row justify-content-end">
                          <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary">Ajouter</button>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- / Content -->
{% endblock %}

src/GestionAchats/templates/Achats/list_order.html
{% extends "Achats/base.html" %}
{% load static %}
{% block content %}

          <!-- Content wrapper -->
          <div class="content-wrapper">
            <!-- Content -->

            <div class="container-xxl flex-grow-1 container-p-y">
              <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Commandes/</span> Afficher</h4>
              <div class="card">
                <div class="table-responsive text-nowrap">
                  <table class="table">
                    <thead>
                      <tr>
                        <th>Commande</th>
                        <th>Client</th>
                        <th>Produits</th>
                        <th>Prix</th>
                        <th>Action</th>
                      </tr>
                    </thead>
                    <tbody class="table-border-bottom-0">
                      {% for order in orders %}
                            <tr>
                            <td><i class="fab fa-angular fa-lg text-danger me-3"></i> <strong><a href="{% url 'order_detail' order.pk %}">{{ order.pk }}</a></strong></td>
      

                            <td><i class="fab fa-angular fa-lg text-danger me-3"></i> <strong>{{ order.customer }}</strong></td>
                            <td>
                              <ul class="list-unstyled users-list m-0 avatar-group d-flex align-items-center">
                                {% for order_product in order.orderproduct_set.all %}
                                <li> - {{ order_product.product }}</li>
                            {% endfor %}

                              </ul>
                            </td>
                            <td><span class="badge bg-label-primary me-1">{{ order.total_price}}€</span></td>
                            <td>
                                <div class="dropdown">
                                <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown"><i class="bx bx-dots-vertical-rounded"></i></button>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="{% url 'add_product_order' order.pk %}"><i class="bx bx-add-to-queue me-1 "></i> Ajouter</a>
                                    <a class="dropdown-item" href="{% url 'delete_order' order.pk %}"><i class="bx bx-trash me-1"></i> Supprimer</a>
                                </div>
                                </div>
                            </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
            <!-- / Content -->


            <div class="content-backdrop fade"></div>
          </div>
          <!-- Content wrapper -->
{% endblock %}

src/GestionAchats/templates/Achats/order_detail.html
{% extends "Achats/base.html" %}
{% load static %}
{% block content %}

          <!-- Content wrapper -->
          <div class="container-xxl flex-grow-1 container-p-y">


            <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Commandes/</span> Afficher Detail</h4>
            <div class="row">
            <!-- Inline text elements -->
            <div class="col">
            <div class="card mb-4">
            <h5 class="card-header">Détails de la commande #{{ order.pk }}</h5>
            <div class="card-body">
            <table class="table table-borderless">
            <tbody>
              <tr>
                <td class="align-middle"><small class="text-light fw-semibold">Client:</small></td>
                <td class="py-3">
                  <p class="mb-0"> {{ order.customer }}</p>
                </td>
              </tr>
              <tr>
                <td class="align-middle"><small class="text-light fw-semibold">Produits:</small></td>
                <td class="py-3">
                  {% for order_product in order.orderproduct_set.all %}
                    <p class="mb-0"> {{ order_product.product }} - Quantité: {{ order_product.quantity }}</p>
                {% endfor %}
                </td>
              </tr>
              <tr>
                <td class="align-middle"><small class="text-light fw-semibold">Prix total:</small></td>
                <td class="py-3">
                  <p class="mb-0"><mark>{{ order.total_price }}</mark></p>
                </td>
              </tr>
              <tr>
              
            </tbody>
            </table>
            </div>
            </div>
            </div>
            </div>
            
            
              
            </div>
          <!-- Content wrapper -->
{% endblock %}

src/GestionAchats/templates/Achats/orders.html
{% extends "Achats/base.html" %}
{% load static %}
{% block content %}
          <!-- Content wrapper -->
          <div class="content-wrapper">
            <!-- Content -->

            <div class="container-xxl flex-grow-1 container-p-y">
              <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Commandes/</span> Afficher</h4>
              <div class="card">
                <h5 class="card-header">Liste des commandes de <strong>{{ name }}</strong></h5>
                <div class="table-responsive text-nowrap">
                  <table class="table">
                    <thead>
                      <tr>
                        <th>Commande</th>
                        <th>Client</th>
                        <th>Produits</th>
                        <th>Prix</th>
                        <th>Action</th>
                      </tr>
                    </thead>
                    <tbody class="table-border-bottom-0">
                      {% for order in orders %}
                            <tr>
                            <td><i class="fab fa-angular fa-lg text-danger me-3"></i> <strong><a href="{% url 'order_detail' order.pk %}">{{ order.pk }}</a></strong></td>
      

                            <td><i class="fab fa-angular fa-lg text-danger me-3"></i> <strong>{{ order.customer }}</strong></td>
                            <td>
                              <ul class="list-unstyled users-list m-0 avatar-group d-flex align-items-center">
                                {% for order_product in order.orderproduct_set.all %}
                                <li> - {{ order_product.product }}</li>
                            {% endfor %}

                              </ul>
                            </td>
                            <td><span class="badge bg-label-primary me-1">{{ order.total_price}}€</span></td>
                            <td>
                                <div class="dropdown">
                                <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown"><i class="bx bx-dots-vertical-rounded"></i></button>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="{% url 'add_product_order' order.pk %}"><i class="bx bx-add-to-queue me-1 "></i> Ajouter</a>
                                    <a class="dropdown-item" href="{% url 'delete_order' order.pk %}"><i class="bx bx-trash me-1"></i> Supprimer</a>
                                </div>
                                </div>
                            </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
            <!-- / Content -->


            <div class="content-backdrop fade"></div>
          </div>
          <!-- Content wrapper -->
{% endblock %}